
export enum TipoDeOperacion{
    SUMA, RESTA, MULTIPLICACION, DIVISION, MENOSUNARIO,
    INCREMENTO,DECREMENTO, MAYOR, MENOR,MAYORIGUAL,
    MENORIGUAL, DOSIGUAL,DISTINTO, OR, AND, NOT, XOR, NEGATIVO
}

export enum Tipo{
    INT,
    BOOLEAN,
    DOUBLE,
    STRING,
    CHAR,
    VOID
}